// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPOS.Infrastructure.Data;

#nullable disable

namespace RestaurantPOS.Migrations
{
    [DbContext(typeof(PosDbContext))]
    [Migration("20260421065936_AddOrderAuditFields")]
    partial class AddOrderAuditFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DepositMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DepositPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DepositPaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TableId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Starters"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "BBQ"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Biryani & Rice"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Desserts"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Masala Chai",
                            Price = 2.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Karak Chai",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Mango Lassi",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Soft Drink (Can)",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Fresh Lime Soda",
                            Price = 2.80m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Samosa (2 pcs)",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Chicken Pakora",
                            Price = 5.50m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Chana Chaat",
                            Price = 4.50m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Chicken Karahi",
                            Price = 11.99m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Lamb Karahi",
                            Price = 13.99m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Chicken Curry",
                            Price = 9.99m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Daal Tarka",
                            Price = 7.99m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Paneer Karahi",
                            Price = 9.50m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Chicken Tikka (Full)",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Seekh Kebab (2 pcs)",
                            Price = 7.50m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Mixed Grill",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Chicken Biryani",
                            Price = 8.99m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Lamb Biryani",
                            Price = 10.99m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Plain Rice",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Pilau Rice",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Gulab Jamun (2 pcs)",
                            Price = 3.99m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Kheer",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Ras Malai",
                            Price = 4.50m
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdultCovers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildCovers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverALabel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoverAPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverBLabel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoverBPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TillNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Number = 9
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Number = 10
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Number = 11
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Number = 12
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantPOS.Domain.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuProduct", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.Domain.Entities.MenuProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
