// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestaurantPOS.Infrastructure.Data;

#nullable disable

namespace RestaurantPOS.Migrations
{
    [DbContext(typeof(PosDbContext))]
    partial class PosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.12");

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("DepositMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("DepositPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DepositPaidAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartySize")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("TableId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Name = "Starters"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Name = "Main Course"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Name = "Rice & Bread"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Name = "Milkshakes"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Name = "Mocktails"
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Name = "Daiquiris"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Samosa (3 pcs)",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Pakora (4 pcs)",
                            Price = 3.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Chicken Pakora (4 pcs)",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Fish Pakora (4 pcs)",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Chapli Kabab (3 pcs)",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Seekh Kabab (4 pcs)",
                            Price = 3.50m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Drum Stick (3 pcs)",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            IsActive = true,
                            Name = "Wings (4 pcs)",
                            Price = 4.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Dal",
                            Price = 6.95m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Lamb Karahi",
                            Price = 8.95m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Palak Chicken",
                            Price = 7.95m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Mince Karahi",
                            Price = 8.95m
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Butter Chicken",
                            Price = 8.95m
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Chicken Manchurian",
                            Price = 7.95m
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            IsActive = true,
                            Name = "Chicken Tikka Karahi",
                            Price = 7.95m
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Plain Rice",
                            Price = 5.00m
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Fried Egg Rice",
                            Price = 5.95m
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Pulao Rice",
                            Price = 7.95m
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Roti",
                            Price = 0.75m
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            IsActive = true,
                            Name = "Naan",
                            Price = 1.50m
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Kheer",
                            Price = 6.95m
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 4,
                            IsActive = true,
                            Name = "Custard Trifle",
                            Price = 5.95m
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "GoGo Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Millionaire Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Hershey’s Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Reese’s Peanut Butter Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Oreo Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Jaffa Cake Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 5,
                            IsActive = true,
                            Name = "Berry Nice Shake",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Miami Sunset",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 31,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Strawberry & Mint",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 32,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Lemon & Lime",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 33,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Pina Colada Mocktail",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 34,
                            CategoryId = 6,
                            IsActive = true,
                            Name = "Mango Mocktail",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 35,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "Strawberry Daiquiri",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 36,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "Mango Daiquiri",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 37,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "Peach Daiquiri",
                            Price = 4.95m
                        },
                        new
                        {
                            Id = 38,
                            CategoryId = 7,
                            IsActive = true,
                            Name = "Blueberry Daiquiri",
                            Price = 4.95m
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdultCovers")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildCovers")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClosedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContextId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoverALabel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoverAPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverBLabel")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CoverBPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsClosed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TableId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TillNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TableId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Table", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            Number = 1
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            Number = 2
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            Number = 3
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            Number = 4
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            Number = 5
                        },
                        new
                        {
                            Id = 6,
                            IsActive = true,
                            Number = 6
                        },
                        new
                        {
                            Id = 7,
                            IsActive = true,
                            Number = 7
                        },
                        new
                        {
                            Id = 8,
                            IsActive = true,
                            Number = 8
                        },
                        new
                        {
                            Id = 9,
                            IsActive = true,
                            Number = 9
                        },
                        new
                        {
                            Id = 10,
                            IsActive = true,
                            Number = 10
                        },
                        new
                        {
                            Id = 11,
                            IsActive = true,
                            Number = 11
                        },
                        new
                        {
                            Id = 12,
                            IsActive = true,
                            Number = 12
                        },
                        new
                        {
                            Id = 13,
                            IsActive = true,
                            Number = 13
                        },
                        new
                        {
                            Id = 14,
                            IsActive = true,
                            Number = 14
                        },
                        new
                        {
                            Id = 15,
                            IsActive = true,
                            Number = 15
                        },
                        new
                        {
                            Id = 16,
                            IsActive = true,
                            Number = 16
                        },
                        new
                        {
                            Id = 17,
                            IsActive = true,
                            Number = 17
                        },
                        new
                        {
                            Id = 18,
                            IsActive = true,
                            Number = 18
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            PasscodeHash = "1234",
                            Role = "Admin",
                            Username = "Admin"
                        });
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Booking", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestaurantPOS.Domain.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Order");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.MenuProduct", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Table", "Table")
                        .WithMany()
                        .HasForeignKey("TableId");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestaurantPOS.Domain.Entities.MenuProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Payment", b =>
                {
                    b.HasOne("RestaurantPOS.Domain.Entities.Order", "Order")
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("RestaurantPOS.Domain.Entities.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
