using RestaurantPOS.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Documents;
using System.Windows.Media;

namespace RestaurantPOS.Services
{
    public class ZReportBuilder
    {
        private readonly SettingsService _settingsService;
        private readonly string _currency;

        public ZReportBuilder(SettingsService settingsService)
        {
            _settingsService = settingsService;
            _currency = settingsService.Settings.CurrencySymbol;
        }

        public FlowDocument Build(ZReportData data)
        {
            var doc = new FlowDocument
            {
                PageWidth = 680,   // A4-friendly — wider than receipt
                FontFamily = new FontFamily("Consolas"),
                FontSize = 13,
                PagePadding = new Thickness(20),
                ColumnGap = 0
            };

            BuildHeader(doc, data);
            BuildOverall(doc, data);
            BuildByOrderType(doc, data);
            BuildByTill(doc, data);
            BuildByUser(doc, data);
            BuildFooter(doc, data);

            return doc;
        }

        // ─── Sections ─────────────────────────────────────────────────────────

        private void BuildHeader(FlowDocument doc, ZReportData data)
        {
            doc.Blocks.Add(Title(_settingsService.Settings.BusinessName));
            doc.Blocks.Add(Center(_settingsService.Settings.AddressLine1));
            doc.Blocks.Add(Center($"{_settingsService.Settings.City} {_settingsService.Settings.Postcode}"));
            doc.Blocks.Add(Center($"Tel: {_settingsService.Settings.PhoneNo}"));
            doc.Blocks.Add(Spacer(10));
            doc.Blocks.Add(Title("*** Z-REPORT ***"));
            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(TwoColumn("Period From:", data.From.ToString("dd/MM/yyyy HH:mm")));
            doc.Blocks.Add(TwoColumn("Period To:", data.To.ToString("dd/MM/yyyy HH:mm")));
            doc.Blocks.Add(TwoColumn("Generated:", DateTime.Now.ToString("dd/MM/yyyy HH:mm")));
            doc.Blocks.Add(TwoColumn("Generated By:", data.GeneratedBy));
            doc.Blocks.Add(TwoColumn("Till:", data.TillNo));

            if (!string.IsNullOrWhiteSpace(_settingsService.Settings.VatNo))
                doc.Blocks.Add(TwoColumn("VAT No:", _settingsService.Settings.VatNo));

            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(DoubleLine());
        }

        private void BuildOverall(FlowDocument doc, ZReportData data)
        {
            var s = data.Overall;

            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(SectionHeader("OVERALL SUMMARY"));
            doc.Blocks.Add(Line());

            doc.Blocks.Add(TwoColumn("Total Orders:", s.OrderCount.ToString()));
            doc.Blocks.Add(TwoColumn("Cancellations:", s.CancelCount.ToString()));
            doc.Blocks.Add(TwoColumn("Adult Covers:", s.AdultCovers.ToString()));
            doc.Blocks.Add(TwoColumn("Child Covers:", s.ChildCovers.ToString()));

            doc.Blocks.Add(Spacer(4));
            doc.Blocks.Add(TwoColumn("Cash Income:", Fmt(s.CashTotal)));
            doc.Blocks.Add(TwoColumn("Card Income:", Fmt(s.CardTotal)));

            if (s.DepositTotal > 0)
                doc.Blocks.Add(TwoColumn("Deposits:", Fmt(s.DepositTotal)));

            doc.Blocks.Add(Line());
            doc.Blocks.Add(TwoColumnBold("TOTAL INCOME:", Fmt(s.GrandTotal)));
            doc.Blocks.Add(TwoColumn("Avg Order Value:", Fmt(s.AverageOrder)));
            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(DoubleLine());
        }

        private void BuildByOrderType(FlowDocument doc, ZReportData data)
        {
            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(SectionHeader("BY ORDER TYPE"));
            doc.Blocks.Add(Line());

            foreach (var s in data.ByOrderType)
            {
                if (s.OrderCount == 0) continue;    // skip empty types

                doc.Blocks.Add(SubHeader(s.Label.ToUpper()));
                BuildSectionRows(doc, s);
                doc.Blocks.Add(Spacer(4));
            }

            doc.Blocks.Add(DoubleLine());
        }

        private void BuildByTill(FlowDocument doc, ZReportData data)
        {
            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(SectionHeader("BY TILL"));
            doc.Blocks.Add(Line());

            foreach (var s in data.ByTill)
            {
                doc.Blocks.Add(SubHeader(s.Label.ToUpper()));
                BuildSectionRows(doc, s);
                doc.Blocks.Add(Spacer(4));
            }

            doc.Blocks.Add(DoubleLine());
        }

        private void BuildByUser(FlowDocument doc, ZReportData data)
        {
            doc.Blocks.Add(Spacer(6));
            doc.Blocks.Add(SectionHeader("BY STAFF MEMBER"));
            doc.Blocks.Add(Line());

            foreach (var s in data.ByUser)
            {
                doc.Blocks.Add(SubHeader(s.Label.ToUpper()));
                BuildSectionRows(doc, s);
                doc.Blocks.Add(Spacer(4));
            }

            doc.Blocks.Add(DoubleLine());
        }

        private void BuildSectionRows(FlowDocument doc, ZReportSection s)
        {
            doc.Blocks.Add(TwoColumn("  Orders:", s.OrderCount.ToString()));
            doc.Blocks.Add(TwoColumn("  Cash:", Fmt(s.CashTotal)));
            doc.Blocks.Add(TwoColumn("  Card:", Fmt(s.CardTotal)));

            if (s.DepositTotal > 0)
                doc.Blocks.Add(TwoColumn("  Deposits:", Fmt(s.DepositTotal)));

            doc.Blocks.Add(TwoColumnBold("  Total:", Fmt(s.GrandTotal)));
        }

        private void BuildFooter(FlowDocument doc, ZReportData data)
        {
            doc.Blocks.Add(Spacer(12));
            doc.Blocks.Add(Center("--- END OF Z-REPORT ---"));
            doc.Blocks.Add(Spacer(4));
            doc.Blocks.Add(Center($"Printed: {DateTime.Now:dd/MM/yyyy HH:mm}"));
            doc.Blocks.Add(Spacer(20));
        }

        // ─── Helpers ──────────────────────────────────────────────────────────

        private string Fmt(decimal value) => $"{_currency}{value:N2}";

        private Paragraph Title(string text) =>
            new Paragraph(new Run(text))
            {
                TextAlignment = TextAlignment.Center,
                FontSize = 16,
                FontWeight = FontWeights.Bold,
                Margin = new Thickness(0)
            };

        private Paragraph SectionHeader(string text) =>
            new Paragraph(new Run(text))
            {
                FontSize = 14,
                FontWeight = FontWeights.Bold,
                Margin = new Thickness(0)
            };

        private Paragraph SubHeader(string text) =>
            new Paragraph(new Run(text))
            {
                FontSize = 13,
                FontWeight = FontWeights.SemiBold,
                Foreground = Brushes.DimGray,
                Margin = new Thickness(0, 4, 0, 2)
            };

        private Paragraph Center(string text) =>
            new Paragraph(new Run(text))
            {
                TextAlignment = TextAlignment.Center,
                Margin = new Thickness(0)
            };

        private Paragraph TwoColumn(string left, string right)
        {
            var p = new Paragraph(new Run(left)) { Margin = new Thickness(0) };
            p.Inlines.Add(new InlineUIContainer(new System.Windows.Controls.TextBlock
            {
                Text = right,
                Width = 620 - (left.Length * 8),
                TextAlignment = TextAlignment.Right
            }));
            return p;
        }

        private Paragraph TwoColumnBold(string left, string right)
        {
            var p = new Paragraph(new Run(left)
            {
                FontWeight = FontWeights.Bold
            })
            { Margin = new Thickness(0) };

            p.Inlines.Add(new InlineUIContainer(new System.Windows.Controls.TextBlock
            {
                Text = right,
                Width = 620 - (left.Length * 8),
                TextAlignment = TextAlignment.Right,
                FontWeight = FontWeights.Bold
            }));
            return p;
        }

        private Paragraph Line() =>
            new Paragraph(new Run(new string('-', 60)))
            {
                Margin = new Thickness(0)
            };

        private Paragraph DoubleLine() =>
            new Paragraph(new Run(new string('=', 60)))
            {
                Margin = new Thickness(0)
            };

        private Paragraph Spacer(double height) =>
            new Paragraph(new Run(string.Empty))
            {
                Margin = new Thickness(0, height, 0, 0)
            };
    }
}
